language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - bower install
services: mongodb

after_script: 
  - istanbul cover ./node_modules/mocha/bin/_mocha server/**/**/ --exclude ./server/api/rooms/socket.io.test.js --exclude ./server/config/socketio.js --exclude ./server/components/errors/index.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage